#' Print or Return Top Documents per Group
#'
#' @description This function displays or returns the top documents for each group based on
#'  the results of document classification.
#'
#' @param classification_result The result of `classify_documents()`. Must contain
#'   walk terms (`return_walk_terms = TRUE` in `classify_document()`).
#' @param documents The full document data to be matched to the classification result for output. Usually the non-tokenized documents.
#' @param doc_id The name of the document identifier used for matching.
#'   Can be a `dplyr::join_by()` function where `classification_result` ID = `a` and `documents` ID = `b`.
#' @param group_name String; The name of the group variable.
#' @param classification_score String; The classification score used for selecting
#'   the top documents Must be present in the data. Returned by `classify_documents()`. Note that this
#'   differs from the `classification_measure` used in `classify_documents()` and `top_group_terms()`
#' @param n The maximum number of documents to print or return per group. (default: 20)
#' @param with_ties Logical indicating tie handling. If TRUE, will include
#'   tied values, potentially leading to more results returned than specified with `n`.
#'   If FALSE, will select tied values at random (default: TRUE).
#' @param mode The mode to operate in, either "print" to print results or
#'   "return" to return a data frame of results (default: "print").
#'
#' @return Depending on `mode`, either prints the results or
#'   returns a data frame containing the specified number of top documents for each group.
#'
#' @examples
#' \dontrun{
#' # the classified_documents object in this example is created by classify_document() - see help(classify_documents)
#' # note that you would usually want to use non-tokenized documents as 'documents'. This data, however, does not come
#' #   with the package. Instead, we paste the tokens of each document together
#'
#' data("de_pol_twitter")
#'
#' top_group_documents(classification_result = classified_documents,
#'                     documents = de_pol_twitter %>% dplyr::summarise(content = paste(lemma, collapse = ","), .by = doc_id),
#'                     doc_id = "doc_id",
#'                     group_name = "ministry_name",
#'                     classification_score = "score_norm",
#'                     n = 20,
#'                     with_ties = FALSE,
#'                     mode = "print")
#' }
#'
#' @export
#'
#' @importFrom rlang arg_match
#' @importFrom dplyr slice_max left_join select relocate everything any_of
#' @importFrom dplyr "%>%"
#' @importFrom purrr iwalk
#' @importFrom data.table as.data.table
#' @importFrom tibble as_tibble
top_group_documents <- function(
  classification_result,
  documents,
  doc_id,
  group_name,
  classification_score,
  n = 20,
  with_ties = TRUE,
  mode = c("print", "return")
){

  # some checks

  rlang::arg_match(mode)

  if ("classified_documents" %in% names(classification_result)) {
    classified_documents <- classification_result$classified_documents
  } else { # if only the classified documents are provided (e.g. because no additional data was generated by classify_documents()), the function can handle this data
    classified_documents <- classification_result
  }

  if (is.character(doc_id) && !(doc_id %in% names(classified_documents))) {
    stop(paste(doc_id, "not found in the classification_results provided."))
  }

  if (is.character(doc_id) && !(doc_id %in% names(documents))) {
    stop(paste(doc_id, "not found in the documents data provided."))
  }

  if (!(group_name %in% names(classified_documents))) {
    stop("Group name not found in the walk_terms data provided.")
  }

  if (!(classification_score %in% names(classified_documents))) {
    stop("Classification Measure not found in the walk_terms data provided.")
  }


  # Printout
  if (mode == "print") {
    cat(paste("\nTop", n, "Documents per", group_name, "\n"))

    classified_documents %>%
      data.table::as.data.table() %>% split(by = group_name) %>%
      purrr::iwalk(\(group, name)
                   {cat(paste0("\n", group_name, " ", name, ":\n"))
                     group %>%
                       dplyr::slice_max(order_by = !!as.name(classification_score),
                                        n = n, with_ties = with_ties) %>%
                       dplyr::left_join(documents, by = doc_id) %>%
                       dplyr::select(!dplyr::any_of(group_name)) %>% # drop group name from printout
                       dplyr::relocate({{classification_score}}, # score first
                                       dplyr::everything()) %>%
                       print()
                     cat("\n===========================================\n")})
  }

  # Return results
  if (mode == "return") {
    classified_documents %>%
      dplyr::slice_max(order_by = !!as.name(classification_score),
                       n = n, with_ties = with_ties,
                       by = !!as.name(group_name)) %>%
      dplyr::left_join(documents, by = doc_id) %>%
      dplyr::relocate({{group_name}}, # group and score first
                      {{classification_score}},
                      dplyr::everything()) %>%
      return()
  }

}
